### ISSUE TITLE
pypi package button still says 0.3.0

### ISSUE THREAD

**Issue by alexanderdean** [jorgebastida/gordon#105]
There's also no 0.4.0 tag - whereas the CHANGELOG says 0.4.0...

**Comment by jorgebastida** [comment]
I did bundle together ``0.4`` few weeks ago... but didn't push it to pypi because couldn't find time to run all integration tests. Because there might be some people using ``0.4`` already... I'm building all recent changes as ``0.5``. Will push to pypi soon.

**Comment by alexanderdean** [comment]
Makes sense!

**Comment by jorgebastida** [comment]
https://pypi.python.org/pypi/gordon/0.5.0

**Comment by alexanderdean** [comment]
Woot!
