### ISSUE TITLE
Stages not working

### ISSUE THREAD

**Issue by jatsrt** [jorgebastida/gordon#11]
When using --stage=??? to apply command, it seems to be ignored.

```
➜  realist-gordon gordon apply --stage=prod
Applying project...
  0001_p.json (cloudformation)
    ✓ No updates are to be performed.
  0002_pr_r.json (custom)
    ✓ code/contrib_lambdas_version.zip (2a16cb60)
    ✓ code/api_faqslist.zip (995f9a9f)
  0003_r.json (cloudformation)
    UPDATE_COMPLETE_CLEANUP_IN_PROGRESS waiting... |                                
Project Outputs:
  LambdaApiFaqslist
    arn:aws:lambda:us-east-1:xxxxxxxxx:function:dev-realist-gordon-r-ApiFaqslist-1S4WC563WH6W9:current
  ApigatewayReaslistapi
    https://45ry8uwz9l.execute-api.us-east-1.amazonaws.com/dev
➜  realist-gordon 
```

**Comment by jorgebastida** [comment]
Hello @jatsrt that's unexpected...  it looks like the ``--stage=prod`` park is not making it into gordon somehow... and it is using the default ``dev`` stage. You can try to run ``$ gordon apply --stage=proc --debug`` to get information about the context that gordon is passing from one template to another.

Which terminal, python version and operating system are you using?

**Comment by jatsrt** [comment]
@jorgebastida so, it was stupidity on my part to some level.

I want to know the stage in my code's context, so add a parameter/context of Stage

Collision with --stage

Remove and works

**Comment by jorgebastida** [comment]
Interesting... that sounds like a bug to me! gordon should (at least) shout with a warning about the collision...

The second interesting thing is that I should make available (in an easy way) the stage of the lambda so it can be pass as context.

Will take note and fix it somehow
