### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by gumuz** [jorgebastida/gordon#126]
Gordon has been BY FAR the nicest way to deploy & configure my lambda functions, but I'm a little worried about it's future.

It seems pretty much abandoned since october, what's your plan with it @jorgebastida ?

I hope this doesn't come across as too negative, I REALLY like the project and can imagine it taking up a lot of your time, so maybe we can work something out.

thanks!

**Comment by nemccarthy** [comment]
+1

**Comment by lsmolic** [comment]
+1

**Comment by jorgebastida** [comment]
Hello! Yes... it is alive! [The last half year of my life has been pretty much chaos](http://www.bbc.co.uk/news/technology-38879239) and I haven't had enough time to take care this :( Sorry!

Now I'm quite more free, and have plans to go all over the open issues and new lambda functionalities and incorporate them into Gordon.

That been said I am really looking forward to find some help in the process, so if somebody out there feels like contributing to this project... that would be much appreciated! Feel free to contact me on me@jorgebastida.com

**Comment by kode4food** [comment]
Fantastic!

**Comment by kerryhatcher** [comment]
@jorgebastida I sent you an email a couple of weeks back offering help, haven't heard back. You still open for support?

**Comment by gumuz** [comment]
same here... For anyone who's looking for an alternative: The Serverless Application Model solves a lot of problems for me.

https://github.com/awslabs/serverless-application-model

http://docs.aws.amazon.com/lambda/latest/dg/automating-deployment.html

**Comment by jorgebastida** [comment]
Sorry! Life always in between me and Gordon :/

Have given a push to the open PR. Will release ``0.6`` in a couple of days with all merged PR.

That been said the amount of time I'll have in the future to solo-develop this project is not going to be huge, so any further help will be appreciated. I have 2 or 3 people in by inbox waiting for a reply in this regard - sorry! Will reply asap.
