### ISSUE TITLE
Add python3.6 runtime

### ISSUE THREAD

**Issue by candlerb** [jorgebastida/gordon#146]
~~~
    _default_runtime = 'python2.7'
    _runtimes = {
        'python': 'python2.7',
        'python2.7': 'python2.7',
        'python2': 'python2.7'
    }
~~~

Seems to be missing [python3.6](http://docs.aws.amazon.com/lambda/latest/dg/python-programming-model-handler-types.html) (and `python3` alias)

**Comment by chuckoy** [comment]
+1, all that's needed to add is the setting, right?

**Comment by jakul** [comment]
@jorgebastida What can we do to get this PR merged?

**Comment by heri16** [comment]
Seems like there are a lot of PR backlogs in gordon. Seems like the project owners need another maintainer who can be active.

**Comment by chuckoy** [comment]
Last commit to master was on 6 Apr so yeah agree.

**Comment by jorgebastida** [comment]
Hi! Just merged this PR, but I indeed need some help. 

I did stop using gordon as part of my full time job months ago, and I can't find much time to continue working on it I'm afraid. 

I'm going to try to have some discipline and help you guys merging anything you might need and do the releases, but I can't see myself implementing lot's of new things in the near future... sorry!
