### ISSUE TITLE
'RequestType': KeyError Traceback

### ISSUE THREAD

**Issue by christophchamp** [jorgebastida/gordon#17]
I ran through the steps outlined in the [Quickstart: Python](http://gordon.readthedocs.io/en/latest/quickstart_py.html). I was able to get the CloudFormation to complete, the Lambda function is created, etc.

```
$ gordon apply
Applying project...
  0001_p.json (cloudformation)
    CREATE_COMPLETE waiting... |                                                    
  0002_pr_r.json (custom)
    ✓ code/contrib_lambdas_version.zip (2b2c3828)
  0003_r.json (cloudformation)
    CREATE_COMPLETE waiting... |                                                    
Project Outputs:
```
However, when I try to test the function using the "Configure test event" (in the AWS Lambda console) with the sample "Hello world" template:
```
{
  "key3": "value3",
  "key2": "value2",
  "key1": "value1"
}
```
I get the following stack trace error:
```
{
  "stackTrace": [
    [
      "/var/task/version.py",
      22,
      "handler",
      "if event['RequestType'] == 'Delete':"
    ]
  ],
  "errorType": "KeyError",
  "errorMessage": "'RequestType'"
}
```
Same error in CloudWatch:
```
Traceback (most recent call last): File "/var/task/version.py", line 22, in handler if event['RequestType'] == 'Delete': KeyError: 'RequestType'
```
Which is a normal Python error for a key (here "RequestType") not residing in the event dictionary.

That error originates in the handler function found in the version.py file starting on line 22:
```
if event['RequestType'] == 'Delete':
        send(event, context, SUCCESS)
        return
```

I am probably missing something obvious. Just posting here to see if anyone knows what I am doing wrong. Thanks!

**Comment by jorgebastida** [comment]
I think you clicked in the wrong lambda in the Lambdas list.

When you have apply your projecto, gordon has created two lambdas. One is your lambda, and the other one is the ``version`` lambda which is an artifact gordon uses internally in order to be able to do everything from Cloudformation (You should not care about this lambda at all)

**Comment by christophchamp** [comment]
Ah. I figured it out. I forgot to uncomment the "firstapp" line in the YAML file:
```
apps:
  - gordon.contrib.lambdas
#  - firstapp
```
That was stupid of me. Sorry for wasting your time.
