### ISSUE TITLE
Error building lambda 'version'!

### ISSUE THREAD

**Issue by rajington** [jorgebastida/gordon#18]
Running into this problem:

```
gordon build --debug
Loading project resources
Loading installed applications
  contrib_lambdas:
    ✓ lambdas:version
  firstapp:
    ✓ lambdas:helloworld
Building project...
  0001_p.json
      cp -Rf * /Users/raj/.gordon/tmp7a1e6o
      echo "[install]
      prefix=" > /Users/raj/.gordon/tmp7a1e6o/setup.cfg
      pip install -r requirements.txt -q -t /Users/raj/.gordon/tmp7a1e6o

Error building lambda 'version'!
cmd: pip install -r requirements.txt -q -t /Users/raj/.gordon/tmp7a1e6o

Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-pLvUZf/cfn-response/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-0t4MeU-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/tmpoClcpV" failed with error code 1 in /private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-pLvUZf/cfn-response/
```

I had to comment out [the line that deletes the requirements](https://github.com/jorgebastida/gordon/blob/master/gordon/resources/lambdas.py#L458) (maybe don't cleanup if using `--debug` or have a second flag?) which is unexpectedly stored in `~/.gordon` (could this go in `_build` as well?) and then ran the install command with maximum verbosity (`pip install -r requirements.txt -q -t /Users/raj/.gordon/tmpMcrEwn --log test.txt`):

```
Collecting cfn-response (from -r requirements.txt (line 1))
  1 location(s) to search for versions of cfn-response:
  * https://pypi.python.org/simple/cfn-response/
  Getting page https://pypi.python.org/simple/cfn-response/
  Looking up "https://pypi.python.org/simple/cfn-response/" in the cache
  Current age based on date: 427
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 427
  Analyzing links from page https://pypi.python.org/simple/cfn-response/
    Found link https://pypi.python.org/packages/4a/43/c36e466a91de38cc7e6b274e00535a7b35ae68730017848dfb167f4703d8/cfn-response-0.0.4.tar.gz#md5=a78d734fe2551a400a87d4ce8749ad05 (from https://pypi.python.org/simple/cfn-response/), version: 0.0.4
    Found link https://pypi.python.org/packages/86/bf/cff7c0a4308b9cff5a73d75d9858a3a2a1ea16a614bb934ba5aeb96d933f/cfn-response-0.0.2.tar.gz#md5=3d2b13e730e6e8b1541b2cf32e61f53b (from https://pypi.python.org/simple/cfn-response/), version: 0.0.2
    Found link https://pypi.python.org/packages/ce/1a/49e98a3c6af11284e7c408e74ac0e57a1b83e87df77db7910569aa9e7e0a/cfn-response-0.0.1.tar.gz#md5=23f3922cde8254b515212ae4a2be4b5f (from https://pypi.python.org/simple/cfn-response/), version: 0.0.1
    Found link https://pypi.python.org/packages/f3/ff/4f00f954e4772ed81f598fd1151825b05cdab515c4211ca4880dd0eebaa2/cfn-response-0.0.3.tar.gz#md5=9cc0f3cf33a7282af2284fa633b0619a (from https://pypi.python.org/simple/cfn-response/), version: 0.0.3
  Using version 0.0.4 (newest of versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4)
  Looking up "https://pypi.python.org/packages/4a/43/c36e466a91de38cc7e6b274e00535a7b35ae68730017848dfb167f4703d8/cfn-response-0.0.4.tar.gz" in the cache
  Current age based on date: 1952
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 1952
  Using cached cfn-response-0.0.4.tar.gz
  Downloading from URL https://pypi.python.org/packages/4a/43/c36e466a91de38cc7e6b274e00535a7b35ae68730017848dfb167f4703d8/cfn-response-0.0.4.tar.gz#md5=a78d734fe2551a400a87d4ce8749ad05 (from https://pypi.python.org/simple/cfn-response/)
  Running setup.py (path:/private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response/setup.py) egg_info for package cfn-response
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/cfn_response.egg-info
    writing pip-egg-info/cfn_response.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/cfn_response.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/cfn_response.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/cfn_response.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/cfn_response.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/cfn_response.egg-info/SOURCES.txt'
  Source in /private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response has version 0.0.4, which satisfies requirement cfn-response from https://pypi.python.org/packages/4a/43/c36e466a91de38cc7e6b274e00535a7b35ae68730017848dfb167f4703d8/cfn-response-0.0.4.tar.gz#md5=a78d734fe2551a400a87d4ce8749ad05 (from -r requirements.txt (line 1))
Installing collected packages: cfn-response
    Running command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-UOPjPW-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/tmpPioLFm
    running install
    error: must supply either home or prefix/exec-prefix -- not both
Cleaning up...
  Removing source in /private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-UOPjPW-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/tmpPioLFm" failed with error code 1 in /private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 880, in install
    spinner=spinner,
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-UOPjPW-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/tmpPioLFm" failed with error code 1 in /private/var/folders/10/frng74qn5dj4vpmr8x76x7fw0000gn/T/pip-build-YZZvSq/cfn-response/
```

key line being `error: must supply either home or prefix/exec-prefix -- not both` which caused me to try: `pip install -r requirements.txt -q --log test.txt` which worked fine.

Because of the multiple directories being involved I'm not sure what your recommendation is to fix it, but removing `-t {target}` from [the pip command in lambdas.py](https://github.com/jorgebastida/gordon/blob/master/gordon/resources/lambdas.py#L592) did seem to work

Anyway, hope this isn't just something dumb on my end because I haven't seen others complaining and I tried to explain all the steps involved. 

Also, great work, was really into "serverless framework" for a while until I switched gears. I'm switching back pretty soon here and this project has a lot of promise, although it'll take a couple of days before I wrap my head around everything with this project.

**Comment by jorgebastida** [comment]
Hello! Interesting issue. Are you using hombrew's python? Apparently there is a know issue (if that is the case). http://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both I'll try to reproduce this locally and try to find a common ground which works both with hombrew's python and any other. There are some suggestions about how to fix this issue in the thread above.

About building the lambdas within temporal directories and not within ``_build``... well there were a few reasons. The most important one is kind-of philosophical: Gordon needs that working directory because most tools like ``pip``, ``npm`` or ``gradle`` need to work with "real" folders... but it is really a sub-product that users should not care... or even be bothered with if the tool is working correctly.

That been said: What about... if the tool is not working correctly and you want to debug what your ``build`` project is doing?

Then yes, I think we should introduce something like... ``$ gordon build --develop`` (name tbd) which helps people develop/debug their build process. If this option is used, gordon should output (and not delete) the temporal folder which has use for each of the lambdas... and perhaps enable "break points" so you need to ``press enter to continue`` between build steps.

From the top of my head Packer does something similar with their ``-debug`` option. See https://www.packer.io/docs/command-line/build.html You basically need to press enter between stages. We could implement something similar quite easily.

Thank you very much for your feedback, will try to put something together :)

**Comment by rajington** [comment]
It was the homebrew issue, thanks!

Also, I had to manually comment out the delete command for it to keep stuff in `.gordon` so it's true most users won't be bothered with it, I was just used to them being in something like `/tmp` but no worries there.

It was actually pretty easy to test against master and modify code, so no rush on the `--develop` option, I'm fine with closing this if you want since it's not pressing.

**Comment by LAMike310** [comment]
@rajington How did you fix your homebrew issue? I followed the StackOverflow directions by making a `pydistutils.cfg` file on the terminal, but I'm still getting the same error.

**Comment by rajington** [comment]
That's all that I needed to do, I put it in my home directory so `~/.pydistutils.cfg`, are you getting the exact error I was? you can run with the debug flag to get a little bit more info `gordon build --debug`

**Comment by jarrydfillmore** [comment]
+1 for me, getting the same error!

**Comment by rajington** [comment]
@jarrydfillmore did you try the `~/.pydistutils.cfg`? and is it the exact same error?

**Comment by jorgebastida** [comment]
@rajington @jarrydfillmore @LAMike310 Just pushed some changes to this branch https://github.com/jorgebastida/gordon/pull/31 

Need to say that I couldn't manage to reproduce this bug after installing python using homebrew, so I'm not 100% sure  this would solve your problem.... but based on the comments in http://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both it might do.

In order to test this branch you should run something similar to (if you run it within a virtualenv... it would be better):

```shell
$ git clone git@github.com:jorgebastida/gordon.git
$ cd gordon
$ git checkout -t origin/bug/homebrew-python
$ python setup.py develop
```

Remember to remove the workaround ``~/.pydistutils.cfg`` and give it a try if you have a moment :)

**Comment by valscion** [comment]
I think I might have the same issue. I have installed python via homebrew and I can fix this by creating the `~/.pydistutils.cfg` file.

I uninstalled gordon (`pip uninstall gordon`), cloned the repository to my machine (master was at commit 0e7d287396d85fc87141b16e594b65fdad944ffa) and ran `python setup.py develop` from there. I still receive this error when I run `gordon build` in my project that is just the hello world example in docs for JS:

```
$ gordon build --debug
Loading project resources
Loading installed applications
  contrib_lambdas:
    ✓ lambdas:version
  firstapp:
    ✓ lambdas:helloworld
Building project...
  0001_p.json
      cp -Rf * /Users/vesa/.gordon/tmp8nvaj5
      pip install --install-option="--prefix=" -r requirements.txt -q -t /Users/vesa/.gordon/tmp8nvaj5

Error building lambda 'version'!
cmd: pip install --install-option="--prefix=" -r requirements.txt -q -t /Users/vesa/.gordon/tmp8nvaj5

/usr/local/lib/python2.7/site-packages/pip/commands/install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 355, in run
    lib_dir = distutils_scheme('', home=temp_target_dir)['purelib']
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

I'm running OS X El Capitan 10.11.5. I'm new to debugging python applications, so if there is anything I can do to help you test fixes for this out, I'd be happy to help :smile:. It surely is a pickle that you aren't able to reproduce this yourself, though 😞

**Comment by warka0** [comment]
I've the exact same error. 😢

**Comment by warka0** [comment]
@jorgebastida I'm not able to build either. Any chances to re-open this issue ? 😄

**Comment by clok** [comment]
+1 I have tried work arounds as well, issue is on Mac OS X 10.11.6 El Cap for me.

**Comment by astewart-twist** [comment]
Did anyone ever figure out how to fix this (without the `~/.pydistutils.cfg` 'fix')?
