### ISSUE TITLE
is the env Isolation by AWS Accounts a pre-requisite to use Gordon?

### ISSUE THREAD

**Issue by JDFagan** [jorgebastida/gordon#19]
I like the feel/simplicity of this tool (vs. Serverless which feels more complicated).  However, before I invest time, I saw section entitled - **Isolation between stages?**:

> ...Putting that to the extreme, and following AWS best practices that means using different AWS accounts. This completely clash with the suggested approach that AWS suggest you to follow with services such as apigateway, where they emphasize to have several "stages" for the same apigateway resource. We disagree and completely ignore that functionality.
> 
> Gordon keeps reproducibility and isolation at it's core. When you apply gordon projects in different stages or regions, you'll deploy completely isolated Cloudformation stacks which will contain an exact and isolated copy of all the resources you have defined.

So, what if I don't have multiple AWS sub-accounts to achieve separation of envs (dev, staging, prod)?  Can I effectively still use the concepts of multiple envs with Gordon but have it make use of just one AWS account?

**Comment by jorgebastida** [comment]
Now that I read that again... I think I didn't phrase that correctly - Yes, you totally can deploy several stages to the same account :)

The reference about using different accounts had the intention to emphasize "how separate" dev and prod should be - the extreme/ideal approach would be to have them in separate accounts... but that doesn't need to be the case at all, no.

Hope this answers your question. Will keep this open until I make that paragraph more clear.

**Comment by JDFagan** [comment]
Great, thanks for clarifying 👍

**Comment by jorgebastida** [comment]
I've rephrase this section of the readme, https://github.com/jorgebastida/gordon/commit/a4319778d927dbda864cb816941e97d4afce8870

Hope is clear now :)

**Comment by JDFagan** [comment]
Line 87: Just a final clarification - you mentioned the following: "...for services such as apigateway, where they emphasize to have several "stages" for the same apigateway resource. We disagree and completely ignore that functionality because we believe is the wrong approach."

So, if you completely "ignore that functionality" AND one still uses only one AWS account, how are multiple envs achieved still (i.e., dev, beta, prod)?  Do you achieve it via your "contexts" concept?

Thanks!
