### ISSUE TITLE
Files not copied in the tmp directory for gordon run

### ISSUE THREAD

**Issue by pmontrasio** [jorgebastida/gordon#32]
Run the telegram api example with ```gordon run```

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.context'
```

This happens because the ```.context``` file is not copied to the temporary directory created by gordon to run locally the script and 

```
var gordon_context = JSON.parse(fs.readFileSync('.context', 'utf8'));
```

fails.

I modified the bot not to read the token from ```.context```. I pass the token directly in the ```new TelegramBot(token)``` constructor and it works, both locally and on AWS.

**Comment by jorgebastida** [comment]
Hello @pmontrasio yes... that is the case unfortunately :(

Few days ago @lukemelia suggested something similar in https://github.com/jorgebastida/gordon/issues/29

My plan is to make this possible as part of ``0.3`` as soon as I fix some of the most obvious bugs already raised for ``0.2.x``.
