### ISSUE TITLE
Mock LambdaContext in Node loader missing context.fail()

### ISSUE THREAD

**Issue by chrislopresto** [jorgebastida/gordon#35]
Our `context.fail()` commands are bombing when we run failing node lambdas locally via `gordon run`. For now we're polyfilling locally to work around this. We'd like to PR a better fix when we have some time, but for now we're opening this issue.

### Relevant Neck of the Woods
https://github.com/jorgebastida/gordon/blob/master/gordon/loaders/node.js#L24-L26

**Comment by jorgebastida** [comment]
When writing the loader I followed this "spec" http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html which doesn't mention the ``.fail()`` method I'm afraid :( (nor the succeed ) 

Perhaps this is a ``node`` pattern that I am missing...

As a quick fix... adding a new ``fail`` method might solve your problem, right?

**Comment by jorgebastida** [comment]
This is quite rudimentary... feedback welcome! https://github.com/jorgebastida/gordon/pull/39

**Comment by chrislopresto** [comment]
Excellent, thanks! That's what we had in mind.. we just hadn't forked, poked around for test coverage yet, etc.
