### ISSUE TITLE
Requirements.txt being ignored.

### ISSUE THREAD

**Issue by empath** [jorgebastida/gordon#36]
I'm building a python lambda and have a structure like this:

ls

--project:
 settings.yml
 --app:
   code.py
   requirements.txt
   settings.yml

running gordon build;gordon apply successfully uploads the lambda function, but it seems to have totally ignored requirements.txt, causing the lambda function to not run.
Is there a way to force it to use requirements or otherwise troubleshoot why it's skipping it?

**Comment by empath** [comment]
I figured out the issue.  In settings, if you point code: at a file instead of at a directory, it doesn't look for requirements.txt

**Comment by jorgebastida** [comment]
That's it. if you point ``code`` to a filename instead of a directory gordon will **not** look for requirements. 

Using a filename as code is suppose to cover super-simple lambdas which don't have any requirement, modules etc...
