### ISSUE TITLE
'pip search gordon' yields versions not on this repo

### ISSUE THREAD

**Issue by JDFagan** [jorgebastida/gordon#38]
Installation docs mentions using pip.  But doing a pip search on gordon yields a version not mentioned on your Github:

```
$ pip search gordon
JoeLogTools (0.4.0)  - Joseph Gordon's decorating logging metaclass.
gordon (0.0.1)       - gordon is a simple framework for creating server-less applications using AWS services
```
https://github.com/jorgebastida/gordon/releases
https://github.com/jorgebastida/gordon/releases/tag/0.1
https://github.com/jorgebastida/gordon/releases/tag/0.2.0

So, it version 0.0.1 for pip pointing to tag/0.1 or tag/0.2.0?  Is it always the latest or have you just forgot to update pip releases to current recent releases that have been tagged above?

**Comment by jorgebastida** [comment]
omg! That is quite a surprise.
- ``0.0.1`` was only created in pypi so I could reserve the name while developing this
- ``0.1.0`` was a pre-release version I shared with a small circle of people
- ``0.2.0`` was the release version.

It is true that doing ``pip search gordon`` returns what you posted... but if you do ``pip install gordon `` you'll get ``0.2.0`` installed (just tried this on a fresh computer).

I might cockup something... but pypi shows '' 0.2.0`` https://pypi.python.org/pypi/gordon  so I'm not sure what could be wrong...

**Comment by JDFagan** [comment]
I can confirm that installing it does indeed install version 0.2.0:

```
$ pip search gordon
JoeLogTools (0.4.0)  - Joseph Gordon's decorating logging metaclass.
gordon (0.0.1)       - gordon is a simple framework for creating server-less applications using AWS services
  INSTALLED: 0.2.0
  LATEST:    0.0.1
```

I'm unsure why it reports latest as 0.0.1.  I'll ping back if I learn more why that may be..

**Comment by JDFagan** [comment]
Note, it does list latest as 0.2.0 with PyCharm.  So its just my command line where I see the latest incorrectly..

![gordon via pycharm](https://cloud.githubusercontent.com/assets/121693/15838708/7190406a-2bf4-11e6-9783-ef9f1f9eaec7.png)

**Comment by jorgebastida** [comment]
I'm going to release ``0.2.1`` probably today... will check after registering the new version if the output of pip changes...

**Comment by jorgebastida** [comment]
Just pushed ``0.2.1`` and pip still shows ``0.0.1``... will investigate, but this is quite weird!

**Comment by jorgebastida** [comment]
Oh ok... it looks like it is a bug in ``pypy`` which is quite broken I'm afraid :(
* https://github.com/pypa/pip/issues/3767
* https://bitbucket.org/pypa/pypi/issues/412/my-package-doesnt-show-up-in-search
