### ISSUE TITLE
Support for CORS 

### ISSUE THREAD

**Issue by athrun** [jorgebastida/gordon#56]
Is it currently possible to set up CORS for an API deployed through gordon?

The gordon documentation is very vague when it comes to API Gateway and I wasn't able to set up the required headers on the response (namely Access-Control-Allow-Origin, Access-Control-Allow-Headers and Access-Control-Allow-Methods).

**Comment by elkelk** [comment]
PR is up: https://github.com/jorgebastida/gordon/pull/70
Conversation is at: https://github.com/jorgebastida/gordon/issues/68
