### ISSUE TITLE
Zipping large archives is very slow

### ISSUE THREAD

**Issue by ninjabear** [jorgebastida/gordon#89]
```{python}
output = six.BytesIO()
zf = zipfile.ZipFile(output, 'w')

for basedir, dirs, files in os.walk(destination):
    relative = os.path.relpath(basedir, destination)

    for filename in files:
        source = os.path.join(destination, basedir, filename)
        relative_destination = os.path.join(relative, filename)
        zf.write(source, relative_destination)

zf.close()
output.seek(0)
```
This code for creating an archive [from here](https://github.com/jorgebastida/gordon/blob/master/gordon/resources/lambdas.py#L468-L480) is very slow when creating large archives, especially with lots of files. On my machine a 60MB directory with a few thousand files (scala project) took at least 30 minutes before I gave up! 

I'm not sure why this is, but it is repeatable. Replacing the above code with this:

```{python}
with tempfile.SpooledTemporaryFile('wb') as tmp:
    with zipfile.ZipFile(tmp, 'w') as zf:
        for basedir, dirs, files in os.walk(destination):
            relative = os.path.relpath(basedir, destination)
            for filename in files:
                source = os.path.join(destination, basedir, filename)
                relative_destination = os.path.join(relative, filename)
                zf.write(source, relative_destination)
    tmp.seek(0)
    output = six.BytesIO(tmp.read())

output.seek(0)
```

Reduces the archiving time on the same data to a few seconds. I will submit a PR shortly!

**Comment by jorgebastida** [comment]
wow... have no idea why ``ZipFile`` might perform that bad using ``BytesIO`` instead of a temp file... this is quite interesting :D I would totally think the opposite might happen (using memory instead of disk) but... we are obviously missing something here!

**Comment by ninjabear** [comment]
I know! It's bizarre, I too expected the `BytesIO` way to be faster. Thanks for taking a look at this @jorgebastida !
